### ISSUE TITLE
请问佬是怎么提的apk？

### ISSUE THREAD

**Issue by tony31444** [fR0Z863xF/fuuleaHD_MDM_Bypass#1]
挺好奇的

**Comment by fR0Z863xF** [comment]
## 抓包或爬虫
### 抓包
抓包仅限于获取我们有的app的链接，下载用的http，直接开热点上wireshark即可；
### 爬虫
领创的api都给人研究烂了，GitHub上就有现成的爬虫，也有用action爬完的结果，直接搜就行（搜索可能需要技巧）。  
注：此处没有贬低领创的意思，只是研究领创api的人很多

**Comment by fR0Z863xF** [comment]
还有我不是佬，我只是个初学者 : )
